name: flutter_inappwebview
description: A Flutter plugin that allows you to add an inline webview, to use an headless webview, and to open an in-app browser window.
version: 6.2.0-beta.3
homepage: https://inappwebview.dev/
repository: https://github.com/pichillilorenzo/flutter_inappwebview
issue_tracker: https://github.com/pichillilorenzo/flutter_inappwebview/issues
funding:
  - https://inappwebview.dev/donate/
topics:
  - html
  - webview
  - webview-flutter
  - inappwebview
  - browser

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_platform_interface: ^1.4.0-beta.3
    # path: ../flutter_inappwebview_platform_interface
  flutter_inappwebview_android: ^1.2.0-beta.3
    # path: ../flutter_inappwebview_android
  flutter_inappwebview_ios: ^1.2.0-beta.3
    # path: ../flutter_inappwebview_ios
  flutter_inappwebview_macos: ^1.2.0-beta.3
    # path: ../flutter_inappwebview_macos
  flutter_inappwebview_web: ^1.2.0-beta.3
    # path: ../flutter_inappwebview_web
  flutter_inappwebview_windows: ^0.7.0-beta.3
    # path: ../flutter_inappwebview_windows
  flutter_inappwebview_linux: ^0.1.0-beta.1
    # path: ../flutter_inappwebview_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  generators:
    path: ../dev_packages/generators

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_inappwebview_android
      ios:
        default_package: flutter_inappwebview_ios
      macos:
        default_package: flutter_inappwebview_macos
      web:
        default_package: flutter_inappwebview_web
      windows:
        default_package: flutter_inappwebview_windows
      linux:
        default_package: flutter_inappwebview_linux

  assets:
    - packages/flutter_inappwebview/assets/t_rex_runner/t-rex.html
    - packages/flutter_inappwebview/assets/t_rex_runner/t-rex.css
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages

false_secrets:
  - /test_node_server/*.pem
  - /test_node_server/*.pfx