name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.1
  source_gen: ^1.2.5
  flutter_inappwebview_internal_annotations: ^1.1.0

dev_dependencies:
  build_runner: ^2.2.1
  build_test: ^2.1.5
  test: ^1.21.1