name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.0
  source_gen: ^4.0.0
  analyzer: ^9.0.0
  collection: any
  flutter_inappwebview_internal_annotations: ^1.3.0
    # path: ../flutter_inappwebview_internal_annotations

dev_dependencies:
  build_runner: ^2.4.12
  build_test: ^3.0.0
  test: ^1.25.8